- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-solver-build-container-images
        - nebulous-optimiser-solver-hadolint
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-solver-upload-container-images
        - nebulous-optimiser-solver-hadolint
        - nox-linters
    promote:
      jobs:
        - nebulous-optimiser-solver-promote-container-images
